### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Tannister** [AntonioDePau/GHDS_ModdingTool#15]
Trying to compile using the given .bat, msbuild raises the error CS0103 in gh\gh.cs(324,45) ['GetCustomSongFolder' does not exist in the current context]

**Comment by AntonioDePau** [comment]
Let me see what I can find.

In the meantime, @Tannister, do you have the VS Build Tools 2022 installed?

**Comment by Tannister** [comment]
> do you have the VS Build Tools 2022 installed?

Yes, its installed in its default location.
