### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Tannister** [AntonioDePau/GHDS_ModdingTool#17]
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -1.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Helpers.UpdateLine(String text)
   à NDS.GH.<>c__DisplayClass3_0.<ManageSongs>b__7(String x)
   à System.Collections.Generic.List`1.ForEach(Action`1 action)
   à NDS.GH.ManageSongs(GHGAME ghgame, ARMFile ARM9, FNTFile FNT, FSINDEXFile FSINDEX, List`1 Songs, ModdingSettings moddingSettings)
   à NDS.NDSFile..ctor(String file, ModdingSettings mods)
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Helpers.UpdateLine(String text)
   à NDS.GH.<>c__DisplayClass3_0.<ManageSongs>b__7(String x)
   à System.Collections.Generic.List`1.ForEach(Action`1 action)
   à NDS.GH.ManageSongs(GHGAME ghgame, ARMFile ARM9, FNTFile FNT, FSINDEXFile FSINDEX, List`1 Songs, ModdingSettings moddingSettings)
   à NDS.NDSFile..ctor(String file, ModdingSettings mods)
You can now press any key or close this window!

This happen when dropping *any* rom in the current release (also happen when using one I compiled myself)

**Comment by Tannister** [comment]
Some of the file tree is created.
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/b98a1314-1af4-44ce-9617-a168e11bf93f)

**Comment by AntonioDePau** [comment]
Wow, that's actually an error with the CMD output... Amazing, never seen that before! I'll apply some Math.**Max** to avoid that, thanks!
