### ISSUE TITLE
Pink Screen when importing Big songs

### ISSUE THREAD

**Issue by Tannister** [AntonioDePau/GHDS_ModdingTool#20]
Big charts seems to overwrite unintended parts of the game.
Video showing what happens and chart files (pre-converted to BHDS, not compressed) are linked below.

[Obsidian.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12050417/Obsidian.zip)
https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/cd1f7925-4910-4e12-8ac2-d26344740798

(This is with the 1.0.3 of the tool)

**Comment by Tannister** [comment]
In the case of the video, Yellow was the replaced song.

**Comment by Tannister** [comment]
Here are some More results using Obsidian : 

| Replaced Song | Result |
|-|-|
| Age Of the Understatement | Emulator Crash After VV Logo |
| Call Me When You're Sober | White Screen Before Licence Text |
| Club Foot                 | White Screen After Licence Text |
| Everything About You      | Softlock on Licence Text |
| Excuse Me Mr.             | Softlock on Licence Text |
| Fascination               | Softlock on Licence Text |
| Feel Good Inc.            | Softlock during Licence Text Fade Out |
| First Date                | Softlock during Licence Text Fade Out |
| Fly Away                  | Softlock after Gameplay Instructions page 2 |
| Girlfriend                | Softlock after Gameplay Instructions Page 1 |
| Golden Touch              | Softlock after Gameplay Instructions Page 1 |
| Grace Kelly               | Softlock after Gameplay Instructions page 2 |
| I Predict A Riot          | Softlock after Gameplay Instructions Page 1 |
| Lets Get It Started       | Softlock after Gameplay Instructions page 2 |
| Manhattan                 | Softlock after Gameplay Instructions page 2 |
| Monkey Wrench             | Softlock after Gameplay Instructions Page 1 |

| | |

**Comment by AntonioDePau** [comment]
I had no issues whatsoever with Grace Kelly, did you take the (E) song and simply brought it over to the (US) version of BHDS?

Your table of replaced songs, were they all replaced at the same time, or different modded ROMs with only one song modded at a time?

**Comment by Tannister** [comment]
Only one song replaced with Obsidian at a time

**Comment by AntonioDePau** [comment]
Also, could you confirm the CRC of your clean unmodded BHDS ROM? (US) version?

**Comment by AntonioDePau** [comment]
> Only one song replaced with Obsidian at a time

Okay, so the songs might be fine by themselves, but yeah, Obsidian is causing some kind of incorrect RAM offset.

**Comment by Tannister** [comment]
its not the (US) version I have, but the (EU) (EN,FIGS)

MD5    : 8beafeb0d5e06bd7212068c26abea454
SHA256 : 96e83de5203ca4590ebe29b29073bfc5d541bbf44bd824b4850c06616849f55d
